processor-toolbox:

    processors:

        - type: egg-processor
          name: egg1
        - type: forward-fftw
          name: fft1
        - type: convert-to-power
          name: to-ps1

        - type: egg-processor
          name: egg2
        - type: forward-fftw
          name: fft2
        - type: convert-to-power
          name: to-ps2

        - type: data-accumulator
          name: acc
        - type: gain-variation
          name: gainvar

        - type: variable-spectrum-discriminator
          name: discrim
        - type: sequential-track-finder
          name: seq-tr-clust
        - type: track-proc-ws
          name: tr-proc-ws
        - type: root-tree-writer
          name: trw

    connections:

        # Header processing
        - signal: "egg1:header"
          slot: "fft1:header"

        - signal: "egg1:ts"
          slot: "fft1:ts-fftw"

        # First egg processing
        - signal: "fft1:fft"
          slot: "to-ps1:fs-fftw-to-psd"

        - signal: "to-ps1:psd"
          slot: "acc:ps"

        - signal: "acc:ps-finished"
          slot: "gainvar:ps-var"

        - signal: "gainvar:gain-var"
          slot: "discrim:gv"

        # Second egg processing
        - signal: "egg2:header"
          slot: "fft2:header"

        - signal: "egg2:ts"
          slot: "fft2:ts-fftw"

        - signal: "fft2:fft"
          slot: "to-ps2:fs-fftw-to-psd"

        - signal: "to-ps2:psd"
          slot: "discrim:ps-pre"

        - signal: "discrim:disc-1d"
          slot: "seq-tr-clust:disc-1d"

        - signal: "discrim:disc-1d"
          slot: "trw:disc-1d"             # Writing discriminated points to ROOT tree

        - signal: "seq-tr-clust:seq-cand"
          slot: "tr-proc-ws:seq-cand"

        - signal: "tr-proc-ws:track"
          slot: "trw:proc-track"          # Write processed tracks to a ROOT tree



    run-queue:
        - egg1
        - egg2


egg1:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 0
    slice-size: 4096
    progress-report-interval: 10000

fft1:
    transform-flag: ESTIMATE

acc:
    number-to-average: 0
    signal-interval: 0

gainvar:
    normalize: false
    min-frequency: 0
    max-frequency: 100e6
    fit-points: 50

egg2:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 0
    slice-size: 4096
    progress-report-interval: 10000

fft2:
    transform-flag: ESTIMATE

discrim:
    min-frequency: 5e6         
    max-frequency: 95e6        
    sigma-threshold: 5
    normalize: true
    neighborhood-radius: 2


seq-tr-clust:
    min-frequency: 5e6
    max-frequency: 95e6
    initial-slope : 350e6                # slope of a track with 1 point
    slope-method: weighted-first-point-ref
    n-slope-points: 10
    time-gap-tolerance: 0.2e-3
    frequency-acceptance: 56e3
    trimming-threshold: 7.5            # snr threshold for the first and last point of a candidate
    min-points: 6
    min-slope: 0


trw:
    output-file: "TracksAndEvents.root"
    file-flag: recreate
